system:
  host: "0.0.0.0"
  port: 8080
  env: release
mysql:
  host: 127.0.0.1
  port: 3306
  db: gwa
  user: root
  password: "123123"
  config: "charset=utf8&parseTime=True&loc=Local"
  log_level: dev
jwt:
  signing-key: 8c231fd6-ddf8-4b53-ada9-b4d9ffb59774
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus
logger:
#  日志等级
  level: info
#  日志前缀
  prefix: '[gwa]'
#  日志存放目录
  director: log
#  是否显示行号
  show_line: true
#  是否显示文件路径
  log_in_console: true
